version: '3.7'
services:
  mysql-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest_admin
      MYSQL_USER: admin_user
      MYSQL_PASSWORD: admin_password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
